spring:
  cloud:
    kubernetes:
      client:
        namespace: carloszamo077-dev
  application:
    name: helloboot-discovery

simplecalculator:
  ribbon:
    eureka:
      enabled: false
    client:
      enabled: true
    ServerListRefreshInterval: 5000
