spring:
  cloud:
    kubernetes:
      client:
        namespace: carloszamo077-2-dev
  application:
    name: helloboot-discovery

ribbon:
  http:
    client:
      enabled: true
      
service-scheduler:
  ribbon:
    retryableStatusCodes: 404,502,500
    eureka:
      enabled: false
    client:
      enabled: true
    ServerListRefreshInterval: 5000
    ConnectTimeout: 500
    ReadTimeout: 500
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 3